Account grupoCliente1 = new Account(ExternalId__c = '1', AccountNumber = '10');
upsert grupoCliente1 ExternalId__c;

Account grupoCliente2 = new Account(ExternalId__c = '2', AccountNumber = '20');
upsert grupoCliente2 ExternalId__c;

Account grupoCliente3 = new Account(ExternalId__c = '3', AccountNumber = '30');
upsert grupoCliente3 ExternalId__c;

Account grupoCliente4 = new Account(ExternalId__c = '4', AccountNumber = '40');
upsert grupoCliente4 ExternalId__c;